---
title: "Week 1 Lecture Notes"
author: "Sherri Verdugo"
date: "August 24, 2014"
output:
  html_document:
    highlight: espresso
    theme: cosmo
    toc: yes
    toc_depth: 3
  pdf_document:
    highlight: espresso
    toc: yes
    toc_depth: 3
  word_document: default
---

## Course Description

* SOCI 303 Statistics for the Social Sciences

*Description*: Prerequisites: completion of G. E. Categories III.A.1 and III.C.1. Techniques for the elementary statistical analysis of social data. Description and inferential measures include tests, chi-square, analysis of variance, contingency table analysis and linear regression.
Units: (3)

This class is not difficult, but you will be required to retain the information you learn. Take notes, ask questions, inquire. This is the learning process so you will need to recall math concepts. If enough people are interested, I will run a math review boot camp during the second week during office hours. In addition, I will provide extra notes for math concepts that will be key in our class.


## Syllabus 

Let's take a few minutes to go over the syllabus and expectations for the class. 

## Surviving Statistics

Statistics is a method based class. Meaning that you will learn methods that will carry you through to the next topic. This semester will build on top of knowledge you already know and will learn. If you are stuck, confused, or you want to talk about statistics, I encourage you to come to my office.

* Statistics is defined as: a set of methods where one wants to infer facts about a population using _noisy_ statistical data where uncertainty must be accounted for.

* Motivations: 
  * Elections (who will win an election...prediction)
  * Clinical research (will a certain medication perform better?)
  * Does the weight of a car impact the mpg of the car?
  * Hypothesis testing...using evidence based methods!


## When things go wrong with research

* Can things go wrong:
  * Hormone replacement therapy study in 2002 stopped for negative events.
  * Newborns and extra corporeal membrane oxygenation treatment (ECMOs)... sample sized based criticism.
  
* How to avoid things going "wrong"...
  * Reproducible research
  * Documentation
  * Following procedures
  * Correct interpretation


## Expectations

* Overview of the field of statistics
* Provide an overview of the scientific method
* Statistical reasoning learned from observations
* Techniques for dealing with uncertainties in drawing conclusions
* Making sense of data
* Familiarity with SPSS 

Over the course, you will find that some topics may be more difficult than others. Just remember to look back at your notes because a missing step can often lead to the wrong answer.



## Class Organization

Chapter  |  Title                   | Topic
---------|--------------------------|-------
Ch. 1    | How we reason            | Scientific Method
Ch. 2    | Levels of Measurement    | NOIR
Ch. 3    | Defining Variables       | Operational Definitions
Ch. 4    | Central Tendency         | Mean, Median, Mode
Ch. 5    | Measuring Dispersion     | Range, Variance, St. Deviation
Ch. 6    | Contingency Tables       | Construction, Regrouping
Ch. 7    | Statistical Inference    | Tests of Significance
Ch. 8    | Probability Distributions| z test & t test
Ch. 9    | Two Sample t-test        | Independent vs. Dependent
Ch. 10   | One-Way ANOVA            | Analysis of Variance
Ch. 11   | Measuring Association    | Interpreting Association
Ch. 12   | Chi-Square               | Tests for Contingency
Misc. 1  | Correlation              | Does not imply causation
Misc. 2  | Regression               | Prediction



## Overview of course

Each week we will be dividing our time between lecture and hands on experience. Check the course websites for more information.

Item              | Points Possible    
------------------|---------------------
Attendance        | 100 Points (based on rosters)
Participation     | 50 Points 
Homework          | 100 Points
Homework Desc.    | 5 assignments @ 20 points each
Exams             | 300 points
Exam Desc.        | 2 exams @ 150 points each
Writing Assignment| 150 points 2 components
W.A. Desc.        | Draft 75 Points
W.A. Desc.        | Final 75 Points

Total Points available: 
`Points: 100 + 50 + 100 + 300 + 150 = 700`

Please make sure you check the course website for deadlines and other course information. 


## Questions

You can reach me at: sverdugo@fullerton.edu

Phone: 657.278.6728
